### ISSUE TITLE
Outbound crashes on Android 8+

### ISSUE THREAD

**Issue by egor-n** [outboundio/android-sdk#10]
Outbound doesn't show any notification and crashes the app (if it is in the background) whenever you send a push notification:

```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=DISPLAY_NOTIF pkg=* (has extras) }: app is in background uid UidRecord{e2eb6b u0a166 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
       at io.outbound.sdk.OutboundPushReceiver.handleOutboundIntent(OutboundPushReceiver.java:1087)
```

**Comment by fmedlin** [comment]
The `OutboundService` is implemented as an `IntentService`. It could be implemented as a `JobService` and scheduled with `JobScheduler`. That would only work for sdk 21+ though.

Another option is [Firebase JobDispatcher](https://github.com/firebase/firebase-jobdispatcher-android#user-content-firebase-jobdispatcher-) which will work down to sdk 9. However, that  requires play-services and I don't how the maintainers feel about that dependency. If that isn't a problem, it might be the easiest fix.

Another option would be to refactor the `Notification` assembly outside of the service. There's a lot of resource wrangling going on in the service, but I'm not aware of any time constraints in FCM message handling.

**Comment by fmedlin** [comment]
So, I just noticed that the README for 0.3 notes play-services dependency. So, maybe the Firebase JobDispatcher is worth doing?

**Comment by ryan-scott-dev** [comment]
For now I'm keen on using the Firebase Job Dispatcher as we already have the play services dependency

**Comment by ryan-scott-dev** [comment]
[Release 0.4.0](https://github.com/outboundio/android-sdk/releases/tag/0.4.0) fixes this issue.
See the [Migration Guide](https://github.com/outboundio/android-sdk/blob/master/docs/migrating.md) for information on the changes required.

Outbound documentation on our SDK will be updated shortly.
