### ISSUE TITLE
minSdkVersion too high

### ISSUE THREAD

**Issue by brucexia** [outboundio/android-sdk#2]
why and is it possible to set it to something lower, like maybe 19?

**Comment by w3b5urf3r** [comment]
@brucexia their support reply to me saying you can use the fcm branch by including the library in your project. when you do so, you'll notice that the build.gradle doesn't have the configuration needed to be included in this way.
If you managed to refactor the build.gradle file please share.
thanks

**Comment by autonomousapps** [comment]
Yeah, what the hell? Who writes a library with a minSdk of 24?!

**Comment by ryan-scott-dev** [comment]
I've just released [0.3.0](https://github.com/outboundio/android-sdk/releases/tag/0.3.0) which relaxes the minSDKVersion down to 19 (done in #11).
