### ISSUE TITLE
Add support for Android O Notification Channels

### ISSUE THREAD

**Issue by egor-n** [outboundio/android-sdk#6]
See [official documentation](https://developer.android.com/preview/features/notification-channels.html) for more information.

The important point is:
> When you target Android O, you must implement one or more notification channels to display notifications to your users.

...otherwise, the notifications will not show up at all.

**Comment by ryan-scott-dev** [comment]
[Release 0.4.0](https://github.com/outboundio/android-sdk/releases/tag/0.4.0) fixes this issue.
See the [Migration Guide](https://github.com/outboundio/android-sdk/blob/master/docs/migrating.md) for information on the changes required.

Outbound documentation on our SDK will be updated shortly.
